CREATE DATABASE IF NOT EXISTS upload_file_db
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE upload_file_db;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);